### ISSUE TITLE
 Error: 'wst_oper' is not defined

### ISSUE THREAD

**Issue by selenepatani** [xapple/waste_flow#3]
Hello. I just installed the package through conda and when I run these commands
```
from waste_flow.analysis import waste_ana

df = waste_ana.dry_long
```
I get this error
```
Exception has occurred: UndefinedVariableError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
name 'wst_oper' is not defined
```
Doing a roughly debug it seems related to the column "wst_oper" which is not anymore present in the pandas dataframe defined.

Could you please help me? Thank you in advance!

Selene

**Comment by xapple** [comment]
What should happen:

<img width="647" alt="should" src="https://github.com/xapple/waste_flow/assets/649288/b2370167-2450-470c-a0a4-9d4bfb7c4497">

What is happening:

<img width="1120" alt="does" src="https://github.com/xapple/waste_flow/assets/649288/79122494-275f-4ab3-be07-1b5678912237">

Now how is this possible? The `waste_flow` package didn't change since two years. So it means that something else changed. It could be the TSV format that are downloaded from eurostat, but this doesn't appear to be the case. Therefor, we can conclude that it's one of the packages used as a dependency of `waste_flow`. Here the culprit is `pandas`, which has changed a lot recently. 

To fix the problem, cap the versions of the dependencies to the same versions that were used during development.

     conda install pandas==1.5.3

If you want to use the latest version of pandas you need to fix the code here:

https://github.com/xapple/waste_flow/blob/master/waste_flow/treatment.py#L98

**Comment by selenepatani** [comment]
I still have the same issue using pandas = 1.5.3
```
Exception has occurred: UndefinedVariableError
name 'wst_oper' is not defined
```

**Comment by xapple** [comment]
Them it's a different issue then the one caused by the `pandas` version. However, I am unable to reproduce your bug, and as you can see here the tests are passing for the current master branch: 

https://github.com/xapple/waste_flow/actions/runs/5241378579

Maybe if you can detail the steps needed to produce the error.

**Comment by selenepatani** [comment]
Below the error I get when I use the last version of plumbing 2.11.2. I tried to downgrade it to version 2.10.6 and now the code is running correctly.
```
>>> from waste_flow.analysis import waste_ana
>>> df = waste_ana.dry_long
Traceback (most recent call last):
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\pandas\core\computation\scope.py", line 198, in resolve
    return self.resolvers[key]
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\collections\__init__.py", line 891, in __getitem__   
    return self.__missing__(key)            # support subclasses that define __missing__
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\collections\__init__.py", line 883, in __missing__   
    raise KeyError(key)
KeyError: 'wst_oper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\pandas\core\computation\scope.py", line 209, in resolve
    return self.temps[key]
KeyError: 'wst_oper'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\waste_flow\analysis.py", line 130, in dry_long
    df = self.dry_mass
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\plumbing\cache.py", line 86, in __get__
    else:                                      result = self.func(instance)
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\waste_flow\analysis.py", line 122, in dry_mass
    result = self.spread_waste * dry_coef
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\plumbing\cache.py", line 169, in __get__
    else:                                      result = self.func(instance)
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\waste_flow\analysis.py", line 91, in spread_waste
    df = self.kilograms
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\waste_flow\analysis.py", line 66, in kilograms
    df = self.combined
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\waste_flow\analysis.py", line 52, in combined
    trt = waste_trt.normalized
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\plumbing\cache.py", line 86, in __get__
    else:                                      result = self.func(instance)
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\waste_flow\treatment.py", line 93, in normalized
    df = self.long_format
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\plumbing\cache.py", line 86, in __get__
    else:                                      result = self.func(instance)
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\waste_flow\treatment.py", line 52, in long_format
    df = self.filtered
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\waste_flow\treatment.py", line 41, in filtered
    df = df.query("wst_oper in @trt_selected")
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\pandas\util\_decorators.py", line 331, 
in wrapper
    return func(*args, **kwargs)
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\pandas\core\frame.py", line 4463, in query
    res = self.eval(expr, **kwargs)
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\pandas\util\_decorators.py", line 331, 
in wrapper
    return func(*args, **kwargs)
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\pandas\core\frame.py", line 4601, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\pandas\core\computation\eval.py", line 
353, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\pandas\core\computation\expr.py", line 
813, in __init__
    self.terms = self.parse()
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\pandas\core\computation\expr.py", line 
832, in parse
    return self._visitor.visit(self.expr)
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\pandas\core\computation\expr.py", line 
415, in visit
    return visitor(node, **kwargs)
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\pandas\core\computation\expr.py", line 
421, in visit_Module
    return self.visit(expr, **kwargs)
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\pandas\core\computation\expr.py", line 
415, in visit
    return visitor(node, **kwargs)
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\pandas\core\computation\expr.py", line 
424, in visit_Expr
    return self.visit(node.value, **kwargs)
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\pandas\core\computation\expr.py", line 
415, in visit
    return visitor(node, **kwargs)
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\pandas\core\computation\expr.py", line 
723, in visit_Compare
    return self.visit(binop)
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\pandas\core\computation\expr.py", line 
415, in visit
    return visitor(node, **kwargs)
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\pandas\core\computation\expr.py", line 
536, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\pandas\core\computation\expr.py", line 
456, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\pandas\core\computation\expr.py", line 
415, in visit
    return visitor(node, **kwargs)
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\pandas\core\computation\expr.py", line 
549, in visit_Name
    return self.term_type(node.id, self.env, **kwargs)
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\pandas\core\computation\ops.py", line 85, in __init__
    self._value = self._resolve_name()
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\pandas\core\computation\ops.py", line 109, in _resolve_name
    res = self.env.resolve(local_name, is_local=is_local)
  File "C:\Dev\Anaconda3\envs\biomon_data\lib\site-packages\pandas\core\computation\scope.py", line 211, in resolve
    raise UndefinedVariableError(key, is_local) from err
pandas.errors.UndefinedVariableError: name 'wst_oper' is not defined
```

**Comment by xapple** [comment]
Thanks for the stack trace. To get a better view of what is happeneing, I would inspect the contents of the variable `df` in the following frame: `waste_flow\treatment.py line 41`.

Anyways, glad to hear that is it working now by setting the version of the `plumbing` module to a fixed value. All modules should be fixed in fact, and I see in the file `setup.py` that two other modules are marked as: 

    autopaths>=1.4.12
    pymarktex>=1.4.6

These should be changed to specific versions with`==` to avoid breaking updates.
